project:
  type: website

website:
  navbar:
    background: "#6488a4"
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - lists.qmd
      - icon: github
        href: https://github.com/DAboaba
      - icon: linkedin
        href: https://www.linkedin.com/in/daboaba/
format:
  html:
    theme: yeti
    css: styles.css
    highlight-style: zenburn

editor: visual

execute:
  freeze: auto

