project:
  type: website

website:
  title: "shokunin"
  navbar:
    right:
      - about.qmd
      - lists.qmd
      - icon: github
        href: https://github.com/DAboaba
      - icon: linkedin
        href: https://www.linkedin.com/in/daboaba/
format:
  html:
    theme: lumen
    css: styles.css
    highlight-style: zenburn

comments:
  giscus:
    repo: DAboaba/shokunin

editor: visual

execute:
  freeze: auto

