project:
  type: website

website:
  title: "shokunin"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sketchy
    css: styles.css

comments:
  giscus:
    repo: DAboaba/shokunin

editor: visual

