---
title: "Articles"
date: "2024-01-24"
categories: [lists]
---

A running list of articles I've read, am reading, or am planning to read.

To find out more about why I'm doing this and what the symbols to the left of each article mean, check [here](../../posts/about_lists/index.qmd).

**Work**

-   [ ] [Meta doing God's work](https://medium.com/@ignacio.de.gregorio.noblejas/meta-is-doing-gods-work-releases-shockingly-good-coding-models-to-the-world-848975e7d1f0)

-   [ ] [Stop using histograms](https://towardsdatascience.com/6-reasons-why-you-should-stop-using-histograms-and-which-plot-you-should-use-instead-31f937a0a81c)

-   [ ] [Data Fraud Allegations](https://www.theatlantic.com/science/archive/2023/08/gino-ariely-data-fraud-allegations/674891/#)

-   [ ] [Getting Shit Done as a Software Engineer](https://careercutler.substack.com/p/how-to-get-done-as-a-software-engineer?utm_source=post-email-title&publication_id=1504485&post_id=140424691&utm_campaign=email-post-title&isFreemail=true&r=mwwv8&utm_medium=email)

-   [ ] [How Uber finds nearby drivers](https://newsletter.systemdesign.one/p/how-does-uber-find-nearby-drivers?utm_source=post-email-title&publication_id=1511845&post_id=139367048&utm_campaign=email-post-title&isFreemail=true&r=mwwv8&utm_medium=email)

-   [ ] [Mastering System Design](https://substack.com/@systemdesignone/note/c-46521743?utm_source=feed-email-digest)

-   [ ] [Anomaly Detection in Time-Series Analysis](https://medium.com/aimonks/anomaly-detection-for-time-series-analysis-eeecd6282f53)

-   [ ] [What is Good Code?](https://medium.com/@todbotts.triangles/what-is-good-bad-code-an-illustrated-example-for-non-programmers-1222b600a0f0)

-   [ ] [Causal Machine Learning for Creative Insight](https://netflixtechblog.com/causal-machine-learning-for-creative-insights-4b0ce22a8a96)

-   [ ] [How to Learn Deeply in Programming](https://lampmaa22.medium.com/the-key-to-learning-deeply-in-programming-c6085b25f072)

-   [ ] [Pareto's Law in EDA Plots](https://medium.com/gdsc-babcock-dataverse/20-of-eda-plots-data-scientists-use-80-of-the-time-abe7b2ff5cc2)

-   [ ] [Causal Machine Learning in Marketing](https://medium.com/@heinrichkoegel/causal-machine-learning-in-marketing-12dcd91ec24e)

-   [ ] [Making R code faster](https://hookedondata.org/posts/2017-11-30_making-r-code-faster-a-case-study/)

-   [ ] [Recommended Resources for AB testing](https://hookedondata.org/posts/2023-04-19-recommended-resources-for-ab-testing/)

-   [ ] [Guidelines for AB testing](https://hookedondata.org/posts/2018-08-07_guidelines-for-a-b-testing/)

-   [ ] [DS Career Resources](https://hookedondata.org/posts/2021-06-22_career-resources/)

-   [ ] [Advice when applying to DS jobs](https://hookedondata.org/posts/2018-05-29_advice-for-applying-to-data-science-jobs/)

-   [ ] [What's new with ML in production](https://vickiboykis.com/2024/01/15/whats-new-with-ml-in-production/)

-   [ ] [What is ML engineering](https://newsletter.pragmaticengineer.com/p/what-is-ml-engineering)

-   [ ] [The ML toolset](https://newsletter.pragmaticengineer.com/p/the-machine-learning-toolset)

-   [ ] [Useful R functions](https://www.computerworld.com/article/3184778/6-useful-r-functions-you-might-not-know.html)

-   [ ] [FUNctional programming tricks in httr](https://irene.rbind.io/post/fun-prog-httr/)

-   [ ] [Explain XGBoost to me](https://towardsdatascience.com/xgboost-regression-explain-it-to-me-like-im-10-2cf324b0bbdb)

-   [ ] [Visualizing Decision Trees](https://explained.ai/decision-tree-viz/index.html)

-   [ ] [Column Names as Contracts](https://emilyriederer.netlify.app/post/column-name-contracts/)

-   [ ] [Immutable Documentation](https://www.etsy.com/codeascraft/etsys-experiment-with-immutable-documentation)

-   [ ] [Assertr](https://docs.ropensci.org/assertr/index.html)

-   [ ] [Pointblank](https://github.com/rstudio/pointblank)

-   [ ] [RMarkdown-driven Development](https://emilyriederer.netlify.app/post/rmarkdown-driven-development/)

-   [ ] [Stacked Diffs](https://newsletter.pragmaticengineer.com/p/stacked-diffs?utm_source=substack&utm_medium=email)

-   [ ] [The productivity impact of AI coding tools](https://newsletter.pragmaticengineer.com/p/ai-coding-tools?utm_source=substack&utm_medium=email)

-   [ ] [Billion Row Challenge](https://ibis-project.org/posts/1brc/)

-   [ ] [Predicting Performance sans Control Group](https://towardsdatascience.com/predict-your-models-performance-without-waiting-for-the-control-group-3f5c9363a7da)

-   [ ] [Frequentists, Bayesians, and Epistemologists](https://vwo.com/stats-blog/the-frequentists-the-bayesians-and-the-epistemologists/)

-   [ ] [How to Build a Data Warehouse in 3 Hours or Less](https://daydream.co/blog/data-shelf-how-to-build-a-data-warehouse-in-3-hours-or-less)

-   [ ] [Many Data Scientists overuse ML and neglect Mathematical Optimisation](https://towardsdatascience.com/stop-overusing-scikit-learn-and-try-or-tools-instead-796d18fc6d85)

-   [ ] [How I’d Learn Machine Learning (If I Could Start Over)](https://towardsdatascience.com/how-id-learn-machine-learning-if-i-could-start-over-c68d697e6a8a)

-   [ ] [Simple and advanced imputation](https://medium.com/@hhuseyincosgun/dealing-with-missing-data-from-zero-to-advanced-4fb734ee5998)

-   [ ] [Stripe Radar](https://stripe.com/blog/how-we-built-it-stripe-radar)

-   [ ] [The Average is Pretty Rare](https://medium.com/@alexobidiegwu/these-greek-math-concepts-are-why-90-of-data-scientists-fail-b3ebcadfa762)

-   [ ] [Staying Up to Date with AI](https://towardsdatascience.com/how-i-stay-up-to-date-with-ai-as-a-data-scientist-4dd6c9b3fb2c)

-   [ ] [Stacked Diffs](https://newsletter.pragmaticengineer.com/p/stacked-diffs?utm_source=substack&utm_medium=email)

-   [ ] [How 0.1% Companies Do Hyperscaling](https://newsletter.systemdesign.one/p/cell-based-architecture?utm_source=post-email-title&publication_id=1511845&post_id=140890481&utm_campaign=email-post-title&isFreemail=true&r=mwwv8&utm_medium=email)

-   [ ] [55 Million Requests per Second With Only 15 Postgres Clusters](https://newsletter.systemdesign.one/p/postgresql-scalability?utm_source=post-email-title&publication_id=1511845&post_id=140362895&utm_campaign=email-post-title&isFreemail=true&r=mwwv8&utm_medium=email)

-   [ ] [Opinionated Analysis Development](https://peerj.com/preprints/3210/)

**Personal**

-   [ ] [The Argentinian Secret Police](https://www.economist.com/1843/2023/12/04/the-secret-police-killed-his-parents-then-one-of-them-adopted-him?utm_medium=social-media.content.np&utm_source=linkedin&utm_campaign=editorial-social&utm_content=discovery.content)

-   [ ] [Revisiting the Luddites](https://www.smithsonianmag.com/history/what-the-luddites-really-fought-against-264412/)

-   [ ] [Heroic Masculinity](https://www.theatlantic.com/ideas/archive/2023/08/heroic-toxic-masculinity-boys/675172/?utm_campaign=the-atlantic&utm_content=true-anthem&utm_medium=social&utm_source=linkedin)

-   [ ] [Haruspex](https://granta.com/haruspex/?utm_source=Sailthru&utm_medium=email&utm_campaign=Lit%20Hub%20Daily:%20December%204%2C%202023&utm_term=lithub_master_list)

-   [ ] [The Problem of Nature Writing](https://www.newyorker.com/culture/the-weekend-essay/the-problem-of-nature-writing?utm_source=Sailthru&utm_medium=email&utm_campaign=Lit%20Hub%20Daily:%20August%2014%2C%202023&utm_term=lithub_master_list)

-   [ ] [How America Got Mean](https://www.theatlantic.com/magazine/archive/2023/09/us-culture-moral-education-formation/674765/)

-   [ ] [The Longest Relationships of Our Lives](https://www.theatlantic.com/family/archive/2023/08/sibling-relationships-change-adulthood/675027/)

-   [ ] [Sibling Rivalry](https://www.theatlantic.com/magazine/archive/2018/11/the-science-of-sibling-rivalry/570811/)

-   [ ] [Cinematic Universes Aren't New](https://www.matthewball.vc/all/marveliadpart1)

-   [ ] [Colonialism & Ancient Rome](https://aeon.co/essays/colonialism-is-built-on-the-rubble-of-a-false-idea-of-ancient-rome?utm_source=pocket-newtab)

-   [ ] [Dissociative Identity Disorder](https://www.thecut.com/2021/08/dissociative-identity-disorder-youtube.html?utm_source=pocket-newtab)

-   [ ] [Draining California Dry](https://www.technologyreview.com/2021/12/16/1041296/california-climate-change-water-drought/?truid=&utm_source=the_download&utm_medium=email&utm_campaign=the_download.unpaid.engagement&utm_term=&utm_content=12-16-2021&mc_cid=1ad26d8e48&mc_eid=ae849b3441)

-   [ ] [Advice for Modern Parents](https://www.theatlantic.com/family/archive/2021/03/hunt-gather-parent-timeless-advice-for-modern-parents/618172/)

-   [ ] [Wellness Review](https://www.theatlantic.com/books/archive/2023/10/wellness-nathan-hill/675657/)

-   [ ] [Destigmatization](https://www.theatlantic.com/ideas/archive/2023/12/destigmatizing-drug-use-mistake-opioid-crisis/676292/)

-   [ ] [Harm Reduction](https://www.theatlantic.com/ideas/archive/2023/06/harm-reduction-decriminalization-fentanyl-meth/674214/)

-   [ ] [Decolonization](https://www.theatlantic.com/ideas/archive/2023/10/decolonization-narrative-dangerous-and-false/675799/?utm_campaign=the-atlantic&utm_content=true-anthem&utm_medium=social&utm_source=linkedin)

-   [ ] [The Neighbors Who Destroyed Their Lives](https://www.theatlantic.com/ideas/archive/2023/12/schweitzers-brothers-murder-conviction-exoneration-hawaii/676910/?utm_campaign=the-atlantic&utm_content=true-anthem&utm_medium=social&utm_source=linkedin)

-   [ ] [500 Days in a Cave](https://www.newyorker.com/magazine/2024/01/29/the-woman-who-spent-five-hundred-days-in-a-cave?utm_brand=tny&utm_social-type=owned&utm_medium=social&utm_source=linkedin)

-   [ ] [Skull and Bones & Equity and Inclusion](https://www.theatlantic.com/ideas/archive/2024/01/yale-skull-and-bones-secret-societies-diversity/677030/?utm_campaign=the-atlantic&utm_content=true-anthem&utm_medium=social&utm_source=linkedin)

-   [ ] [Adopting a Legacy mind-set](https://www.washingtonpost.com/wellness/2024/01/14/legacy-building-ideas/?utm_campaign=wp_post_most&utm_medium=email&utm_source=newsletter&wpisrc=nl_most)

-   [ ] [The super-rich are trying new approaches to philanthropy](https://www.economist.com/special-report/2024/01/10/the-super-rich-are-trying-new-approaches-to-philanthropy)
